version: '3.9'

services:
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - menu-service
      - order-service
    environment:
      - DOCKER=true

  auth-service:
    build: ./auth-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/auth_db
      - DOCKER=true

  menu-service:
    build: ./menu-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/menu_db
      - DOCKER=true

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/order_db
      - DOCKER=true